sudo: false
language: c
env:
  global:
  - MERLIN_VERSION=380.62_1
  - OPENSSL_VERSION=1.0.1u
  - POLARSSL_VERSION=1.2.19-gpl
  - MBEDTLS_VERSION=2.3.0-gpl
  - SHADOWSOCKS_LIBEV_VERSION=2.5.6
  matrix:
  - CRYPTO_LIBRARY=openssl TOOLCHAIN=merlin-mipsel
  - CRYPTO_LIBRARY=polarssl TOOLCHAIN=merlin-mipsel
  - CRYPTO_LIBRARY=mbedtls TOOLCHAIN=merlin-mipsel
cache:
  directories:
  - "$HOME/CACHE"
script: make install TOOLCHAIN=${TOOLCHAIN} MERLIN_VERSION=${MERLIN_VERSION} SHADOWSOCKS_LIBEV_VERSION=${SHADOWSOCKS_LIBEV_VERSION}
  CRYPTO_LIBRARY=${CRYPTO_LIBRARY} OPENSSL_VERSION=${OPENSSL_VERSION} POLARSSL_VERSION=${POLARSSL_VERSION}
  MBEDTLS_VERSION=${MBEDTLS_VERSION}
after_success: cd $HOME && tar zcvf "shadowsocks-libev-${SHADOWSOCKS_LIBEV_VERSION}-${TOOLCHAIN}-{CRYPTO_LIBRARY}.tar.gz" shadowsocks-libev
deploy:
  provider: releases
  api_key:
    secure: hTyjtsmGS48PQ5hXM6qe3J8pLsndgMiOZn4LDyJE+ZJItJk2mhG/zPwDFu5QiqGk7Mi4GjXMMEIRfaczbEn+CYGdiBYIV7YXjjWKuzdX2/xiGBi0+EjEMlLqzkO+Xr7ova9/S6QNR7PeyrYVj5XNORhkk2evtfgBK7UgoYzOt+g2aqu32qF0Eq7/KjOWKn0b89aq05GA9pICO+5LhvPmYNvaWRumXLzVEbDZ/Ey27iNFMtUCx2YIXRc3iBKL2bcYbA9yuYD1e39PMCGhoLzDpSJ6yW0dm64uweooz7ziqp60TPs45X+RnpN29/cRO/3yEh05Qu7pkj9TqIsI+fP6lQXypMQ3KS6cdmlV0e23g7xlFVkcfGbTXR4nbXvsV06aO4gEHvAN7bl8710kPZubShj939STvoXN83/AdUF/k6GL6X2FgozdQevjDn+mM744897naKS76KRF7SxsRkKIWOO4Xaomf3A9RwZ5B2iqxHKtqCxbazRW0Tl8ZLs534lZVDHz75EMBZqDoawuqhGwKBEbfbVwBY5ogsgTTajgT5RXd42jTO8IG+0P14NF7gdQ1TAf7InUoqkiLXY5OXtWJB6TLDmX80rfxjxNHzkt/t9BgYur9QrhHgHZTlRT/rDIXjldXgQVMXQwmuVNbyR563q2qVE1wBCpR+rZ1Fa5bnQ=
  file: "${HOME}/shadowsocks-libev-${SHADOWSOCKS_LIBEV_VERSION}-${TOOLCHAIN}-${CRYPTO_LIBRARY}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
addons:
  apt:
    packages:
    - autoconf
    - automake
    - bison
    - bzip2
    - diffutils
    - flex
    - m4
    - build-essential
    - gawk
    - groff-base
    - libtool
    - libslang2
    - make
    - patch
    - perl
    - pkg-config
    - shtool
    - texinfo
    - zlib1g-dev
    - gettext
    - libexpat1-dev
    - libssl-dev
    - gperf
    - python
    - libxml-parser-perl
    - gcc-multilib
    - libxml2-dev
    - g++-4.4
    - g++-multilib
    - libncurses5-dev
    - libstdc++6-4.4-dev
    - libvorbis-dev
    - g++-4.4-multilib
    - autopoint
    - autogen
    - sed
    - intltool
    - libelf1:i386
    - libglib2.0-dev
    - lib32z1-dev
    - lib32stdc++6
    - wget
