sudo: false
env:
- TOOLCHAIN_FROM: merlin
- MERLIN_VERSION: 380.62_1
- TOOLCHAIN: mipsel-linux-uclibc
- SHADOWSOCKS_LIBEV_VERSION: 2.5.5
- CRYPTO_LIBRARY: openssl-1.0.1u
- CRYPTO_LIBRARY: polarssl-1.2.19-gpl
- CRYPTO_LIBRARY: mbedtls-2.3.0-gpl
- TARBALLS_DIR_TO_HOME: tarballs
cache:
  directories:
  - $HOME/$TARBALLS_DIR_TO_HOME
addons:
  apt:
    packages:
    - autoconf
    - automake
    - bash
    - bison
    - bzip2
    - diffutils
    - file
    - flex
    - m4
    - g++
    - gawk
    - groff-base
    - libncurses-dev
    - libtool
    - libslang2
    - make
    - patch
    - perl
    - pkg-config
    - shtool
    - subversion
    - tar
    - texinfo
    - zlib1g
    - zlib1g-dev
    - git-core
    - gettext
    - libexpat1-dev
    - libssl-dev
    - cvs
    - gperf
    - unzip
    - python
    - libxml-parser-perl
    - gcc-multilib
    - gconf-editor
    - libxml2-dev
    - g++-4.4
    - g++-multilib
    - gitk
    - libncurses5
    - mtd-utils
    - libncurses5-dev
    - libstdc++6-4.4-dev
    - libvorbis-dev
    - g++-4.4-multilib
    - git
    - autopoint
    - autogen
    - sed
    - build-essential
    - intltool
    - libelf1:i386
    - libglib2.0-dev
    - lib32z1-dev
    - lib32stdc++6
    - asciidoc
    - xmlto
    - wget